const mongoose = require('mongoose');

const poItemSchema = new mongoose.Schema({
  partCode: { type: String, default: '' },
  partNo: { type: String, default: '' },
  itemDescription: { type: String, default: '' },
  partDescription: { type: String, default: '' },
  description: { type: String, default: '' },
  specification: { type: String, default: '' },
  cndt: { type: String, default: '' },
  hsn: { type: String, default: '' },
  hsnCode: { type: String, default: '' },
  uom: { type: String, default: 'PCS' },
  qty: { type: Number, default: 1 },
  quantity: { type: Number, default: 1 },
  rate: { type: Number, default: 0 },
  unitPrice: { type: Number, default: 0 },
  discount: { type: Number, default: 0 },
  gst: { type: Number, default: 18 },
  cgst: { type: Number, default: 0 },
  sgst: { type: Number, default: 0 },
  igst: { type: Number, default: 0 },
  deliveryDate: { type: String, default: '' },
  remark: { type: String, default: '' },
  supplier1Price: { type: Number, default: 0 },
  supplier2Price: { type: Number, default: 0 },
  supplier3Price: { type: Number, default: 0 },
  selectedSupplier: { type: String, default: '' }
}, { _id: false, strict: false });

const poApproverSchema = new mongoose.Schema({
  line: { type: String, default: 'Parallel' },
  managerName: { type: String, default: '' },
  stakeholder: { type: String, default: '' },
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  designation: { type: String, default: '' },
  role: { type: String, default: '' },
  status: { type: String, default: 'Pending' },
  dateTime: { type: String, default: '' },
  date: { type: String, default: '' },
  remarks: { type: String, default: '' },
  comments: { type: String, default: '' },
  contactNo: { type: String, default: '' },
  organization: { type: String, default: '' },
  approvedBy: { type: String, default: '' },
  rejectedBy: { type: String, default: '' }
}, { _id: false, strict: false });

const poNppSchema = new mongoose.Schema({
  uniqueSerialNo: { type: String, unique: true, sparse: true },
  requesterName: { type: String, default: '' },
  name: { type: String, default: '' },
  department: { type: String, default: '' },
  emailId: { type: String, default: '' },
  email: { type: String, default: '' },
  requestDate: { type: String, default: '' },
  contactNo: { type: String, default: '' },
  organization: { type: String, default: 'Radiant Appliances' },
  titleOfActivity: { type: String, default: '' },
  purposeAndObjective: { type: String, default: '' },
  amount: { type: Number, default: 0 },
  totalValue: { type: Number, default: 0 },
  remarks: { type: String, default: '' },
  priority: { type: String, default: 'M' },
  employeeId: { type: String, default: '' },
  location: { type: String, default: '' },
  requestPurpose: { type: String, default: '' },
  
  vendorCode: { type: String, default: '' },
  vendorName: { type: String, default: '' },
  vendorAddress: { type: String, default: '' },
  vendorGst: { type: String, default: '' },
  vendorContact: { type: String, default: '' },
  vendorEmail: { type: String, default: '' },
  vendorKindAttn: { type: String, default: '' },
  selectedSupplier: { type: String, default: '' },
  
  orderNo: { type: String, default: '' },
  orderDate: { type: String, default: '' },
  quotRef: { type: String, default: '' },
  prNo: { type: String, default: '' },
  prId: { type: mongoose.Schema.Types.Mixed },
  prDate: { type: String, default: '' },
  rfqNo: { type: String, default: '' },
  purchaser: { type: String, default: '' },
  purchaserMobile: { type: String, default: '' },
  
  billingAddress: { type: String, default: '' },
  billingGst: { type: String, default: '' },
  shippingAddress: { type: String, default: '' },
  shippingGst: { type: String, default: '' },
  
  transporter: { type: String, default: '' },
  taxes: { type: String, default: '' },
  
  items: [poItemSchema],
  stakeholders: [poApproverSchema],
  approvalChain: [poApproverSchema],
  ccList: [{ type: String }],
  ccEmails: [{ type: String }],
  terms: { type: mongoose.Schema.Types.Mixed, default: [] },
  financeRows: { type: mongoose.Schema.Types.Mixed, default: [] },
  deliverySchedule: { type: mongoose.Schema.Types.Mixed, default: [] },
  attachment1: { type: String },
  attachment2: { type: String },
  attachment3: { type: String },
  attachments: { type: Array, default: [] },
  
  status: { type: String, default: 'Pending' },
  source: { type: String, default: 'PO-NPP' },
  approvedAt: { type: Date },
  approvedBy: { type: String },
  approvalComments: { type: String },
  rejectedAt: { type: Date },
  rejectedBy: { type: String },
  rejectionComments: { type: String },
  rejectionReason: { type: String },
  formData: { type: mongoose.Schema.Types.Mixed }
}, { timestamps: true, strict: false });

module.exports = mongoose.model('PoNpp', poNppSchema);